### PR TITLE
Change mapping so that 0xC0000000 is mapped to 0x00000000

### PR DESCRIPTION
**Pull request by mpetch**
- Change mapping so that 0xC0000000-0xC03FFFFF is mapped to 0x00000000-0x003FFFFF instead of being mapped to 0x00100000-0x004FFFFFF.
This simplifies the mapping, the paging and the linker script. This also allows us to remove the identity mapping of the first 4MiB at the start of our kernel in `_start`. To access physical memory in the first 1MiB of memory like the video buffer at 0xB8000, one can now add 0xC0000000 (KERNEL_HIGH_BASE) to a physical address in the first 1MiB to get its virtual address. Virtual address 0xC00B8000 would be the address of the first cell on the screen.
This has the advantage that if your code accidentally references a NULL pointer (reading, writing, or executing) it will page fault since 0x00000000 is no longer marked present in virtual address space. This can assist in finding coding bugs.
- I have marked some inline assembly with a `memory` clobber where there is the potential side effect that some instructions will alter memory in a way the compiler is unaware of.
- Cleanup VGA code to use a global pointer to the video text area. Ensure it is `volatile`. Also mark it as a `const`ant pointer to volatile memory. MMIO(memory mapped IO) like video memory should be marked `volatile`. Marking it a constant pointer can improve code generation. 
- Cleanup Makefile to omit the frame pointer. This can improve code generation by eliminating the frame pointer prologue and epilogue when possible. Build with optimizations on `-O3`. Results in better code generation and optimizations can occasionally help in the discovery of harder to find bugs.
- Remove gdt_flush.s and move it to gdt.c using inline assembly.
- `asm` statements without output operands are implicitly volatile so no need to explicitly specify `volatile`. 
- `in` and `out` instructions need a `"memory"` clobber because using these instructions may alter what appears in memory (ie: MMIO regions).
- Build with `-Wall -Wextra` to produce more warnings on potentially problematic code. 
- Clean up interrupt handers. `CLI` not needed at top of handler. Entries in the IDT that are interrupt gates cause the CPU to
disable interrupts automatically before calling a handler. This is a common mistake in many tutorials.
- `CLD` is needed per the 32-bit System V ABI to ensure string instruction like `MOVS`, `STOS`, `CMPS` move in the forward direction.
- Exceptions aren't external interrupts, therefore you should not be sending EOIs to PICs. Only send EOIs if an external interrupt (IRQ0 to IRQ15) is received.
- Move function `load_lidt` from idt_setup.asm to idt.c using inline assembly. Cleanup idt.c.

### CODE REVIEW

**Comment by IlanVinograd** [comment]
I really appreciate your help. I'm currently busy for the next couple of days, but I’ve reviewed the code so when I would add the (KERNEL_HIGH_BASE) directive to PA It would be the same as refiring to 0x00000000 physical address but because we using paging it's a virtual address 0x00000000 so it can help with catching errors by catching page fault exception.

**Comment by mpetch** [comment]
Correct. 

Not a problem, you don't need to review or commit anything in haste especially if you are busy doing other things. I don't expect quick turn around on pull requests. You can review them and accept/reject them at your leisure.

**Comment by IlanVinograd** [comment]
and kernel start from 0xC0100000 the same way

**Comment by mpetch** [comment]
> and kernel start from 0xC0100000 the same way

Yes, the actual kernel starts at virtual address 0xC0100000 that maps to physical address 0x00100000.

**Comment by IlanVinograd** [comment]
@mpetch There are different algorithms used for the TLB, such as random, FIFO, OPT, LRU, etc. Do you know if it is possible to change the algorithm used for the TLB? And how can I find out which one is currently being used in my system?

**Comment by mpetch** [comment]
On x86 the TLB algorithm is entirely at the discretion of the CPU. I know
of no way to alter it. You could always ask this question on Stackoverflow.

**Comment by IlanVinograd** [comment]
@mpetch And why did you name this array page_directory_low instead of just page_directory?

**Comment by IlanVinograd** [comment]
Did you name it this way to later use multiple directories, and is that really necessary?

**Comment by mpetch** [comment]
> Did you name it this way to later use multiple directories, and is that really necessary?

`init_paging` poses a unique problem. It is the one function that gets called while in the lower half when it is running in the  area of 0x100000. I originally had the initial page structures (arrays) in  a section called `.lowdata` which I have now removed. The 3 original arrays were originally placed in the 0x100000 physical memory region. Since the code has now been modified to remove the identity mapping of the first 4MiB I needed some mechanism to allow `init_paging` to access the initial page arrays in the lower (`_low`) half of memory while also allowing them to be used later on after we are in the higher half.

You should notice in kernel_entry.s I create `page_directory` , `new_page_table`, and `first_page_table` in the `.bss` section. The `.bss` section has addresses in the higher half at 0xC0100000. Of course before paging is enabled our page tables will be in the low memory area above 0x100000. The  `page_directory_low` , `new_page_table_low`, and `first_page_table_low` actually point to the same memory but offset by 0xC0000000. This allows `init_paging` to reference these 3 arrays before paging is enabled using their addresses in the lower half. These arrays names with `_low` on them shouldn't be used at all after `init_paging` is called because we remove the first 4MiB identity mapping and with paging on they are now addressable at higher half addresses at 0xC0100000 and above.

If you now want to access `page_directory` after switching into the higher half (after `init_paging` is called) you will now just need to use `page_directory` and if you needed `new_page_table`, and `first_page_table` will point to arrays with higher half addresses rather than using `page_directory_low`, `new_page_table_low`, and `first_page_table_low` which have virtual addresses in the first 4MiB that are no longer mapped into memory.

**Comment by IlanVinograd** [comment]
@mpetch So, the purpose was only to handle the remapping to the higher half, and now I can't use page_directory_lower to refer.
If needed, I could remap additional directories with a new directory_page, but now page_directory_lower is no longer relevant because it was only used for the initial setup and remapping to 0xC0000000?

**Comment by IlanVinograd** [comment]
page_directory_lower – but if I wanted to dynamically allocate new pages, why can't I use the same directory that I used for remapping the kernel in the beginning, just with new pages? Or is that not considered good practice?

**Comment by IlanVinograd** [comment]
"first_page_table_low, which has virtual addresses in the first 4 MiB that are no longer mapped into memory."

Yes, because you removed the first 4 MiB. However, I can still access it through 0xC0000000. But can I remap page_directory_lower with new tables and reuse it, or will that not work?

**Comment by mpetch** [comment]
Yes, you can still access `first_page_table_low` (points to a physical address) by using `first_page_table` (virtual address). Virtual address in this case = physical address + 0xC0000000. You can access `page_directory_low` via `page_directory` and even modify `page_directory` array to add/remove new entries as you need to allocate more memory. Nothing is preventing you using/modifying `page_directory`.

This brings me to something you are going to have to consider soon. While you have mapped your kernel to the higher half, you are going to have to eventually create new page tables and allocate physical memory for the actual pages. To do that you are going to have to know where all the usable physical memory is so you can find physical memory to map virtually. To do that you will have to use something like int 0x15/AX=0xe820 (see: https://wiki.osdev.org/Detecting_Memory_(x86) ) to create a memory map while in real mode and then pass that to your kernel so that you can parse it and determine the physical pages you can actually allocate. Allocating physical memory would be part of a physical memory management component of your kernel.

**Comment by IlanVinograd** [comment]
@mpetch 👍, so in my stage2.asm, I would need to call int 15h to read the memory map and store it in a buffer, keeping the count of entries in EDI. Then, in protected mode, I would copy the memory map to a known location, let's say 0xC02FFFFF, and pass the EDI register to the kernel. After that, I would create a structure for the memory map entries, parse it, and use it later for memory allocations.

This is needed for physical memory management before implementing the allocation functions like alloc and page_alloc. This seems like the roadmap I'll likely need to follow.

**Comment by IlanVinograd** [comment]
I placed it at the 0x002FFFFF location and then in the kernel enabled paging so it would be referenced from 0xC02FFFFF.

**Review by IlanVinograd — APPROVED** [review]

**Comment by IlanVinograd** [comment]
@mpetch ISR0 and ISR14 don't work, I tested them now. Could this be caused by paging?

**Comment by IlanVinograd** [comment]
The issue was caused by `-Wall -Wextra -O3 -fomit-frame-pointer.`

**Comment by IlanVinograd** [comment]
@mpetch Could you please check my target branch? I added memory detection, but the memory I'm getting seems unusual. Is the memory detected correct? I’ve attached a screenshot of the memory output for reference.

image

**Comment by mpetch** [comment]
I just became aware of the questions here. The fact ` -Wall -Wextra -O3 -fomit-frame-pointer.` causes a problem is almost certainly a bug in your code. As for the memory map it is not correct. The first entry is correct but starting with the second one it is wrong. The second entry should have a base of 0x9FC00 and a length of 0x400. The third entry is also messed up. It is as if the data has shifted after the first entry. When I get a chance today I can look at it.

**Pull request merged**
